spring.application.name=shopsphere

# properties

spring.config.import=optional:file:.env[.properties]


# Database

spring.datasource.url=jdbc:postgresql://localhost:5432/shopsphere_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false


# Flyway

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
#classpath -> src/main/resources


#1 SQL migrations were detected but not run because they did not follow the filename convention.
# Set 'validateMigrationNaming' to true to fail fast and see a list of the invalid file names.